### ISSUE TITLE
The extension does not start the emulator

### ISSUE THREAD

**Issue by Arya-Aghaei** [343max/vscode-android-emulator-launcher#4]
Hi!
I configured the paths correctly and the extension finds the emulators, but when I hit to start, nothing happens

**Comment by 343max** [comment]
I'm a bit short on time right now, so I'm not sure when I'll have time to look into this. Unless something is broken in a really bad way I'm probably going to need a bit more information then "It's not working" - can you try to find more details?

**Comment by Arya-Aghaei** [comment]
@343max Hmmm, I opened developer tool to see if any error shows up in the console... but you know, simply nothing happens when I choose the emulator, Do you have any suggestion on how I can find more details?

**Comment by 343max** [comment]
So I've looked into the issue a bit and I can't reproduce it. Did you make sure that both `androidEmulatorLauncher.emulatorPath` and `androidEmulatorLauncher.adbPath` are correct?
